# Generated by Django 6.0.4 on 2026-04-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('biografija', models.TextField()),
                ('slika', models.ImageField(upload_to='student_images/')),
                ('datum_rodenja', models.DateField()),
                ('mjesto_rodenja', models.CharField(max_length=200)),
                ('mjesto_stanovanja', models.CharField(max_length=200)),
                ('spol', models.CharField(choices=[('M', 'Muški'), ('Ž', 'Ženski')], max_length=10)),
                ('hobi', models.CharField(max_length=200)),
                ('obrazovanje', models.TextField(help_text='Odvojeno novim linijama')),
                ('vještine', models.TextField(help_text='Odvojeno novim linijama')),
                ('vještine_ostale', models.TextField(help_text='Odvojeno novim linijama')),
                ('link_kolega', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Studenti',
            },
        ),
    ]
