# Generated by Django 6.0.4 on 2026-04-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kratko_o',
            field=models.CharField(default='', help_text='Kratko o studentu (prikazuje se na početnoj stranici)', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='ostali_link',
            field=models.URLField(blank=True, help_text='Link na vanjsku web stranicu', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='video',
            field=models.URLField(blank=True, help_text='YouTube ili drugi video link', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='zvuk',
            field=models.FileField(blank=True, help_text='MP3 ili drugi audio format', null=True, upload_to='student_media/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='link_kolega',
            field=models.URLField(blank=True, help_text='Link na drugog studenta', null=True),
        ),
    ]
