# Generated by Django 5.2.8 on 2026-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenti', '0002_student_kratko_o_student_ostali_link_student_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='link_fakultet',
            field=models.URLField(blank=True, help_text='Link na web stranicu fakulteta', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='link_mjesto_rodenja',
            field=models.URLField(blank=True, help_text='Link na Wikipedia ili web stranicu mjesta rođenja', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='link_skola',
            field=models.URLField(blank=True, help_text='Link na web stranicu škole', null=True),
        ),
    ]
