# Generated by Django 5.2.8 on 2026-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenti', '0003_student_link_fakultet_student_link_mjesto_rodenja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='naziv_fakulteta',
            field=models.CharField(blank=True, help_text='Naziv fakulteta (prikazuje se kao link)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='naziv_skole',
            field=models.CharField(blank=True, help_text='Naziv škole (prikazuje se kao link)', max_length=300, null=True),
        ),
    ]
