# Generated by Django 5.2.8 on 2026-05-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenti', '0004_student_naziv_fakulteta_student_naziv_skole'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='link_osnovna_skola',
            field=models.URLField(blank=True, help_text='Link na web stranicu osnovne škole', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='naziv_osnovne_skole',
            field=models.CharField(blank=True, help_text='Naziv osnovne škole (prikazuje se kao link)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='link_skola',
            field=models.URLField(blank=True, help_text='Link na web stranicu srednje škole', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='naziv_skole',
            field=models.CharField(blank=True, help_text='Naziv srednje škole (prikazuje se kao link)', max_length=300, null=True),
        ),
    ]
