# Generated by Django 5.2.8 on 2026-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenti', '0005_student_link_osnovna_skola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='obrazovanje',
            field=models.TextField(blank=True, help_text='Dodatne napomene o obrazovanju (opcionalno)', null=True),
        ),
    ]
